# 1. Numpy VS Python List

In [1]:
l = range(1000000) # return List

In [1]:
import numpy as np

In [3]:
d = np.arange(1000000) #return array

In [4]:
%time for i in range(1,10): r = [x*2 for x in l]

Wall time: 2.46 s


In [5]:
%time for i in range(1,10): r1 = d*2

Wall time: 41.5 ms


# 2. A Multi-Dimensional Array

### ndarray

In [6]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.empty((7,7)) # in empty there might be randomly values be displayed

array([[1.07920176e-311, 1.07921424e-311, 1.07920228e-311,
        1.07919748e-311, 1.07920228e-311, 1.07921247e-311,
        1.07917876e-311],
       [1.07920228e-311, 1.07920228e-311, 1.07921207e-311,
        1.07921159e-311, 1.07921247e-311, 1.07921207e-311,
        1.07921247e-311],
       [1.07921247e-311, 1.07917876e-311, 1.07921159e-311,
        1.07921262e-311, 1.07919772e-311, 1.07917876e-311,
        1.07921208e-311],
       [1.07921159e-311, 1.07921247e-311, 1.07921247e-311,
        1.07919753e-311, 1.07921207e-311, 1.07921248e-311,
        1.07920078e-311],
       [1.07919748e-311, 1.07921247e-311, 1.07921247e-311,
        1.07921159e-311, 1.07921159e-311, 1.07921247e-311,
        1.07921207e-311],
       [1.07921207e-311, 1.07921159e-311, 1.07921248e-311,
        1.07921159e-311, 1.07921247e-311, 1.07921159e-311,
        1.07921207e-311],
       [1.07921247e-311, 1.07921247e-311, 1.07921247e-311,
        1.07921250e-311, 1.07921159e-311, 1.07921250e-311,
        1.07921250

### Convert list into Numpy Array

In [15]:
list_1 = [1,3,5,7,9] 

In [16]:
np.array(list_1)

array([1, 3, 5, 7, 9])

### Range Method in Python there is arange

In [20]:
x = np.arange(1,100,10)
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

### Want to Know the Shape of this Array

In [23]:
x.shape

(10,)

In [24]:
x1 = np.zeros((10,10))

In [25]:
x1.shape

(10, 10)

### Reshape this shape

In [26]:
y = x1.reshape((2,2,5,5))

In [29]:
y #its now converted in 4 dimensional rray

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

### Datatype of Numpy array

In [31]:
y.dtype

dtype('float64')

### check Dimension

In [34]:
y.ndim

4

# 3. Arithematic with ndarray

### vectorization

### Generate Random Numbers

In [36]:
a = np.random.randn((10))

In [37]:
a

array([ 0.33298446,  0.93726212,  0.26815321,  0.0588113 , -0.25526892,
       -0.60158985,  0.10964336,  0.74468215, -0.88297696,  0.21379876])

In [38]:
b = np.random.randn((10))

In [39]:
b

array([-0.6286357 , -0.37749157,  1.23365722, -0.83928731,  0.72036503,
        0.8654916 , -0.09536404, -1.46539128,  1.40261034,  1.93172401])

### Now Add these Elements

In [40]:
a+b

array([-0.29565124,  0.55977055,  1.50181042, -0.78047601,  0.46509611,
        0.26390175,  0.01427932, -0.72070913,  0.51963338,  2.14552277])

### Can Substract these Elements

In [41]:
a-b

array([ 0.96162016,  1.31475369, -0.96550401,  0.89809861, -0.97563396,
       -1.46708145,  0.2050074 ,  2.21007343, -2.2855873 , -1.71792524])

### CAn Multiply

In [42]:
a*b

array([-0.20932592, -0.35380855,  0.33080914, -0.04935958, -0.18388681,
       -0.52067096, -0.01045603, -1.09125073, -1.23847262,  0.4130002 ])

### Can Divide

In [44]:
a/b

array([-0.52969384, -2.48286903,  0.21736444, -0.07007291, -0.35436051,
       -0.69508456, -1.14973486, -0.50817974, -0.62952406,  0.1106777 ])

### Check How Many Elements Are Positive

In [45]:
a>0

array([ True,  True,  True,  True, False, False,  True,  True, False,
        True])

### Array As an Index

In [46]:
# Geting value of elements in original view
a[a>0]

array([0.33298446, 0.93726212, 0.26815321, 0.0588113 , 0.10964336,
       0.74468215, 0.21379876])

# 4. Indexing And slicing

## Indexing

In [47]:
c = np.array([1,2,4,6,9,10])

In [48]:
c[3]

6

### Boolean Indexing

In [50]:
c[c>5]

array([ 6,  9, 10])

In [51]:
c>5

array([False, False, False,  True,  True,  True])

### FAncy Indexing

In [54]:
c[[1,5]] #elements at 1 and 5 index

array([ 2, 10])

In [56]:
c[[4,2]]

array([9, 4])

## Slicing

In [58]:
f = np.random.randn(10,10)

In [60]:
f

array([[ 1.38368205, -1.81214121,  0.10790668,  0.98538078, -0.33575154,
        -1.5646801 ,  1.18367362,  0.12407748, -1.01740624,  1.63634744],
       [ 1.2155855 , -0.73081613,  1.03583085,  1.37499974,  0.66339754,
        -0.00289933, -1.23853901, -2.6981206 , -0.70589536, -1.70993955],
       [-0.89821565,  0.8314473 , -1.15407326, -0.25149656,  1.6261226 ,
        -0.63438839,  0.76905153, -1.08354875,  0.51196542, -0.33782084],
       [-0.14237675, -0.58838582,  0.5719332 , -0.16394668,  0.07075544,
         0.08885549, -0.9505213 , -0.2623605 , -0.89374861, -0.99152789],
       [-1.31453714, -1.14316763,  0.02589796,  0.90176486, -1.02602429,
        -0.3710638 , -0.0372533 ,  1.43527093,  1.60386333,  0.72349359],
       [-0.63591736,  1.59730768,  1.43741447, -1.09945522, -0.94856669,
        -0.2034077 , -0.67098825, -0.09233946, -0.19759786,  0.39384728],
       [-1.07618033, -0.15896569,  0.67054935,  0.33615402,  1.27602326,
        -2.69991675,  2.10324118, -0.85443823

In [62]:
f[0] # 1st Row 

array([ 1.38368205, -1.81214121,  0.10790668,  0.98538078, -0.33575154,
       -1.5646801 ,  1.18367362,  0.12407748, -1.01740624,  1.63634744])

In [64]:
f[0][3] # 1st row 4th column

0.9853807829370342

In [65]:
f[1:10:2] # Odd Rows

array([[ 1.2155855 , -0.73081613,  1.03583085,  1.37499974,  0.66339754,
        -0.00289933, -1.23853901, -2.6981206 , -0.70589536, -1.70993955],
       [-0.14237675, -0.58838582,  0.5719332 , -0.16394668,  0.07075544,
         0.08885549, -0.9505213 , -0.2623605 , -0.89374861, -0.99152789],
       [-0.63591736,  1.59730768,  1.43741447, -1.09945522, -0.94856669,
        -0.2034077 , -0.67098825, -0.09233946, -0.19759786,  0.39384728],
       [-0.93362702, -0.36875838,  0.51365068,  0.92917542, -0.36121147,
        -0.78656428,  0.53014288,  2.41598319,  0.72085729,  0.49443526],
       [-1.02047053,  0.13995104, -0.33410644,  0.87125797, -0.80929556,
        -0.25619021,  0.92192856,  0.71966143, -0.11847496, -0.74610464]])

In [69]:
f[::,0:3] # All Rows and 03 columns

array([[ 1.38368205, -1.81214121,  0.10790668],
       [ 1.2155855 , -0.73081613,  1.03583085],
       [-0.89821565,  0.8314473 , -1.15407326],
       [-0.14237675, -0.58838582,  0.5719332 ],
       [-1.31453714, -1.14316763,  0.02589796],
       [-0.63591736,  1.59730768,  1.43741447],
       [-1.07618033, -0.15896569,  0.67054935],
       [-0.93362702, -0.36875838,  0.51365068],
       [ 0.441451  ,  0.69001777, -1.5314689 ],
       [-1.02047053,  0.13995104, -0.33410644]])

### Now Fill zeros in Ones

In [71]:
g = np.ones([5,5])

In [72]:
g

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [75]:
# 1st row and last row and 1st column and last column should be Skipped
g[1:-1,1:-1] = 0 

In [74]:
g

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# 5. First Element-Wise Array Function

In [3]:
x = np.array([10,9,8,7,6,5])

In [4]:
np.sqrt(x) #Find Square_Root

array([3.16227766, 3.        , 2.82842712, 2.64575131, 2.44948974,
       2.23606798])

In [9]:
np.square(x) #find Square

array([100,  81,  64,  49,  36,  25], dtype=int32)

In [10]:
np.power(x,3) #Find Power and can find square

array([1000,  729,  512,  343,  216,  125], dtype=int32)

In [12]:
np.max(x) #Find Maximum Value From one Array

10

### If u Find Comparasion and find maximum array between 2 arrays

In [13]:
a = np.array([1,4,0,-5,9])

In [20]:
b = np.array([2,1,0,-1,10])

In [21]:
np.maximum(a,b) #find maximum values by caomparison in both arrays

array([ 2,  4,  0, -1, 10])

In [29]:
c = np.array([1,2,14,5,6])

In [31]:
np.maximum(a,b,c) #find maximum values from multiple arrays

array([ 1,  4, 14,  5,  9])

# 6. np.where()

In [33]:
salary = np.array([0,-1,10000,25000,18000])

In [37]:
np.where(salary<2000, "Invalid", salary) #Format = Condition, option_A, option_B

array(['Invalid', 'Invalid', '10000', '25000', '18000'], dtype='<U11')

In [39]:
np.where(salary<2000, 2000, salary) #CAn use integer and String Both

array([ 2000,  2000, 10000, 25000, 18000])

In [40]:
np.where(salary<2000, "Invalid", "Valid")

array(['Invalid', 'Invalid', 'Valid', 'Valid', 'Valid'], dtype='<U7')

# 7. Mathematical and Statistical Method

In [41]:
array_1 = np.array([10,5,1,29,9])

In [43]:
np.sum(array_1)

54

In [44]:
array_1.mean() #Can use by this

10.8

In [45]:
np.mean(array_1)

10.8

In [46]:
np.cumsum(array_1)

array([10, 15, 16, 45, 54], dtype=int32)

In [47]:
np.cumprod(array_1)

array([   10,    50,    50,  1450, 13050], dtype=int32)

In [51]:
array_1>6

array([ True, False, False,  True,  True])

In [53]:
array_1.sum()

54

In [56]:
array_1.all() #Check if all Elements is True

True

In [55]:
array_1.any() #check if any element is TRue

True

In [57]:
array_1

array([10,  5,  1, 29,  9])

In [61]:
np.sort(array_1)

array([ 1,  5,  9, 10, 29])

In [63]:
np.unique(array_1) #If nt repeatable element

array([ 1,  5,  9, 10, 29])

# 8. File Input/Output

In [81]:
x1 = [1,3,5,7,11,13]

In [82]:
x2 = [2,4,6,8,10,12]

In [100]:
x1

[1, 3, 5, 7, 11, 13]

In [66]:
np.save("Numpy_x1", x1)

In [69]:
loadx1 = np.load('Numpy_x1.npy') 

In [101]:
loadx1

array([ 1,  3,  5,  7, 11, 13])

In [95]:
np.savez("Numpy_x1_x2",x1,x2) #Now u got dictionary in Return

In [112]:
loadboth = np.load('Numpy_x1_x2.npz')

In [115]:
loadboth 

In [122]:
list(loadboth.keys())

['arr_0', 'arr_1']

In [124]:
#To Retrieve the value by Keys
b = loadboth['arr_0']
b

array([ 1,  3,  5,  7, 11, 13])

# 9. Linear ALgebra Functions

In [2]:
x = np.random.randn(3,2) #create Matrix of 3x2

In [3]:
y = np.random.randn(2,3)

In [5]:
x


array([[ 1.06788876,  0.27896261],
       [ 0.76479311,  1.49131055],
       [ 0.45381041, -1.16755568]])

In [6]:
y

array([[ 0.81908487,  0.22615201,  0.46835961],
       [ 1.25384191, -0.0468214 ,  0.1950937 ]])

In [9]:
x.transpose() #transpose of x

array([[ 1.06788876,  0.76479311,  0.45381041],
       [ 0.27896261,  1.49131055, -1.16755568]])

In [10]:
x.trace()

2.559199301222744

# 10. Pseduo-Random Number

In [2]:
np.random.seed(7)

In [3]:
np.random.normal(size = (3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [6]:
np.random.uniform(size = (3,4))

array([[0.23030288, 0.54848992, 0.90912837, 0.13316945],
       [0.52341258, 0.75040986, 0.66901324, 0.46775286],
       [0.20484909, 0.49076589, 0.37238469, 0.47740115]])

# 11. Reshape

In [8]:
x = np.random.randn(4,5)

In [9]:
x

array([[ 0.60049852,  1.04939655, -0.41647432, -0.74255353,  1.07247013],
       [-1.65107559,  0.53542936, -2.0644148 , -0.66215934, -1.20421985],
       [ 1.46197563,  1.76616088, -0.32941375,  0.84073324, -0.1799864 ],
       [ 0.56806189, -0.7528372 , -1.7083392 , -1.80309866,  0.38312185]])

In [11]:
x.reshape(2,2,5) #By Defualt it saves into Row Major Order

array([[[ 0.60049852,  1.04939655, -0.41647432, -0.74255353,
          1.07247013],
        [-1.65107559,  0.53542936, -2.0644148 , -0.66215934,
         -1.20421985]],

       [[ 1.46197563,  1.76616088, -0.32941375,  0.84073324,
         -0.1799864 ],
        [ 0.56806189, -0.7528372 , -1.7083392 , -1.80309866,
          0.38312185]]])

In [15]:
y = np.array([0,1,2,3,4,5,6,7,8,9,10,11])

In [23]:
y.reshape(4,3) #By Default is store in C order (Row Major Order)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
y.reshape((4,3), order = 'f') #Fortran Order (Column Major Order)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [30]:
y.reshape((4,3,-1))

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]]])

In [32]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
y.ravel() #convert into 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
x.ravel() #convert into 1D array

array([ 0.60049852,  1.04939655, -0.41647432, -0.74255353,  1.07247013,
       -1.65107559,  0.53542936, -2.0644148 , -0.66215934, -1.20421985,
        1.46197563,  1.76616088, -0.32941375,  0.84073324, -0.1799864 ,
        0.56806189, -0.7528372 , -1.7083392 , -1.80309866,  0.38312185])

In [37]:
y.flatten() #convert into 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
x.flatten() #convert into 1D array

array([ 0.60049852,  1.04939655, -0.41647432, -0.74255353,  1.07247013,
       -1.65107559,  0.53542936, -2.0644148 , -0.66215934, -1.20421985,
        1.46197563,  1.76616088, -0.32941375,  0.84073324, -0.1799864 ,
        0.56806189, -0.7528372 , -1.7083392 , -1.80309866,  0.38312185])

# 12. Concatenate

In [40]:
a = [[1,3,5],[7,9,0]]

In [41]:
arr_1 = np.array(a)

In [43]:
arr_1

array([[1, 3, 5],
       [7, 9, 0]])

In [44]:
b = [[11,13,15],[17,19,10]]

In [45]:
arr_2 = np.array(b)

In [47]:
arr_2

array([[11, 13, 15],
       [17, 19, 10]])

In [53]:
np.concatenate((arr_1,arr_2)) #By Default its axis = 0

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [54]:
np.concatenate((arr_1,arr_2), axis = 1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

## Now same work with the help of hstack and vstack

In [56]:
np.vstack((arr_1,arr_2)) #along x-axis

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [57]:
np.hstack((arr_1,arr_2)) #along y-axis

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

# 13. Split

In [58]:
c = [1,2,3,4,5,6,7,8,9]

In [59]:
d = np.array(c)

In [60]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.split(d,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [62]:
#When U have 2D array

e = [[1,2,3,4,5,6,7,8,9] , [1,2,3,4,5,6,7,8,9]]


In [63]:
f = np.array(e)

In [64]:
f

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
np.split(f,[4,6], axis = 1) #column-Wise Split

[array([[1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[5, 6],
        [5, 6]]),
 array([[7, 8, 9],
        [7, 8, 9]])]

In [68]:
np.split(f,[1], axis = 0) #Row-Wise Split

[array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])]

In [69]:
v = np.array([1,5,7,8])

In [71]:
np.repeat(v,2)

array([1, 1, 5, 5, 7, 7, 8, 8])

In [74]:
np.tile(v,2)

array([1, 5, 7, 8, 1, 5, 7, 8])

#                                             THE END