In [1]:
import numpy as np

In [3]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


#C(B(A(1)))
#A(B(C(1)))
#A().B().C()

In [4]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
print(a.dtype)

int32


In [12]:
a = np.arange(1,13).reshape(3,4).astype('float64')
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [13]:
a = np.arange(1,13).astype(np.float64).reshape(3,4)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [14]:
a = np.arange(1,13, dtype=np.float32).reshape(3,4)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [27]:
np.random.randn(3,3,3) * 5

array([[[  1.39838105,   1.16460817,   1.68361899],
        [ -4.26259156, -12.37034551,   2.56626153],
        [  0.66547341,   2.89699248,   0.11608765]],

       [[ -1.66390399,  -2.63538416,  -5.46537273],
        [ -2.41629555,   3.52411226,  -0.22005478],
        [ -4.34531165,   1.28095002,   4.86324979]],

       [[ -9.35589272,  -5.45470106,  -6.80596882],
        [ -2.41871143,   3.3789788 ,  -2.86361413],
        [  3.03025253,   0.81257558,   3.31634187]]])

In [28]:
a = np.ones((3,3,3), dtype=np.int64)
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int64)

In [29]:
a = np.zeros((3,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [31]:
a.shape

(3, 3, 3)

In [32]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [39]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
np.ones_like(a) * 2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [42]:
np.ones_like(a) + 4

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [47]:
np.full((3,3,3), 5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [48]:
np.full_like(a, 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [50]:
np.empty((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
np.empty_like(a)

array([[1936020512,  175269236,  538976288],
       [ 538976288,  538976288, 1702063205],
       [ 538970682,  538976288,  538976288],
       [ 538976288, 1634869280,  543519593],
       [1920234561, 1953849961, 1920091493],
       [ 573076079, 1969516397, 2065720684],
       [ 545092129,  544432488, 1629515630],
       [1769108596, 1702131042,  537535008],
       [ 538976288,  538976288,  538976288]])

In [60]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [61]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

np.identity??

# Data Types for ndarrays

In [65]:
a = np.arange(1,13, dtype='int')
print(a.dtype)

int32


In [64]:
a = np.arange(1,13, dtype=np.int64)
print(a.dtype)

int64


In [66]:
a = np.arange(1,13, dtype='i8')
print(a.dtype)

int64


In [67]:
a = a.astype(np.float64)
print(a.dtype)

float64


In [68]:
a = np.arange(1,28, dtype='g').reshape((3,3,3))
print(a)
print(a.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]]
float64


In [69]:
np.full_like(a, 5, dtype=a.dtype)

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]], dtype=float64)

In [70]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [74]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [75]:
a[a % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [80]:
a[(a%3==0) | (a%5==0)]

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27])

In [81]:
a[(a%3==0) & (a%5==0)]

array([15])

In [82]:
a[~(a%3==0)]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [83]:
a[(~a%3==0)]

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [84]:
a = np.array([1,3,5,6,8])
b = np.array([True, False, True,False,False])
a[~b]

array([3, 6, 8])

In [85]:
a = np.array([1,3,5,6,8])
b = [True, False, True,False,False]
a[~b]

TypeError: bad operand type for unary ~: 'list'

# Basic Indexing And Slicing

# Class 04

1. Stacking 
2. Split
3. Important Method

In [2]:
a = np.arange(1,7)
b = a+5

In [5]:
print(a,b,sep = '\n')


[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


In [6]:
a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.stack((a,b))

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [7]:
a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.stack((a,b), axis=1)

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [8]:
a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.stack((a,b))

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [9]:
print(np.stack((a,b), axis=1))
np.column_stack((a,b))

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]
 [ 6 11]]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [10]:
print(np.stack((a,b), axis=0))
np.row_stack((a,b))

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [11]:
a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.hstack((a,b))

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [12]:
a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.vstack((a,b))
#stack axis 0
#row_stack
#vstack

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
np.block([a,b]) # hstack, columstack

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [16]:
a = np.arange(1,2*2*2+1).reshape((2,2,2))
b = a + 5
print(a,b, sep='\n->Second\n')

np.dstack((a,b))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
->Second
[[[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


array([[[ 1,  2,  6,  7],
        [ 3,  4,  8,  9]],

       [[ 5,  6, 10, 11],
        [ 7,  8, 12, 13]]])

In [17]:
a = np.arange(6*6).reshape(6,6)
print(a)
np.split(a, 3, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [18]:
a = np.arange(6*6).reshape(6,6)
print(a)
np.split(a, 2, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [19]:
a = np.arange(6*6).reshape(6,6)
print(a)
np.split(a, 6, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]])]

In [21]:
a = np.arange(6*6).reshape(6,6)
print(a)
np.split(a, 2, axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [22]:
a = np.arange(2*2*2).reshape(2,2,2)
print(a)
np.dsplit(a,2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]),
 array([[[1],
         [3]],
 
        [[5],
         [7]]])]

In [23]:
a = np.arange(2*2*2).reshape(2,2,2)
print(a)
np.split(a, 2, axis=2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]),
 array([[[1],
         [3]],
 
        [[5],
         [7]]])]

# Broad Casting

In [24]:
a = np.random.randint(1,10,size = (3,5))

In [25]:
a

array([[4, 5, 7, 7, 7],
       [5, 8, 7, 9, 7],
       [7, 6, 4, 8, 2]])

In [26]:
a+4

array([[ 8,  9, 11, 11, 11],
       [ 9, 12, 11, 13, 11],
       [11, 10,  8, 12,  6]])

In [32]:
b = np.full_like(a, 5)
print(a, b, sep='\n')
a + b

[[4 5 7 7 7]
 [5 8 7 9 7]
 [7 6 4 8 2]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


array([[ 9, 10, 12, 12, 12],
       [10, 13, 12, 14, 12],
       [12, 11,  9, 13,  7]])

# Table 4-6. Array set operations

In [33]:
a = np.random.randint(1,10, size=20)
a

array([5, 9, 1, 5, 4, 4, 7, 9, 2, 6, 5, 5, 4, 5, 1, 5, 8, 4, 8, 9])

In [34]:
np.unique(a)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [35]:
a = np.random.randint(1,10, size=20)
b =  np.random.randint(1,10, size=5)
print(a,b, sep='\n')

[True if x in a else False for x in b]

[1 6 2 1 3 3 4 2 8 1 5 4 1 5 9 1 3 6 5 4]
[2 6 9 3 5]


[True, True, True, True, True]

In [36]:
a = np.random.randint(1,10, size=20)
b =  np.random.randint(1,10, size=5)
print(a,b, sep='\n')

np.in1d(b, a)

[8 3 1 9 1 7 5 2 9 3 6 1 4 3 3 7 5 4 2 1]
[6 2 2 5 9]


array([ True,  True,  True,  True,  True])

In [40]:
c = np.in1d(b, a)
c = c.reshape((1,-1))
c
# np.apply_along_axis(lambda x:"A" if x else "B",1,arr=c)
np.where(c==True,"A","B")

array([['A', 'A', 'A', 'A', 'A']], dtype='<U1')

In [41]:
a = np.random.randint(1,10, size=20)
b =  np.random.randint(1,10, size=5)
print(a,b, sep='\n')

["A" if x in a else "B" for x in b]

[2 8 2 2 3 6 8 1 4 7 3 7 7 8 2 2 2 5 2 1]
[4 9 5 4 9]


['A', 'B', 'A', 'A', 'B']

In [42]:
a = np.random.randint(1,10, size=20)
b =  np.random.randint(1,10, size=5)
print(a,b, sep='\n')
np.setdiff1d(b, a)

[2 2 7 5 7 6 8 5 6 4 8 1 8 1 3 3 3 8 1 3]
[6 2 5 8 1]


array([], dtype=int32)

In [43]:
#XOR
# 0 0 ->0
# 1 0 ->1
# 0 1 ->1
# 1 1 ->0
print(a,b, sep='\n')
np.setxor1d(b, a)

[2 2 7 5 7 6 8 5 6 4 8 1 8 1 3 3 3 8 1 3]
[6 2 5 8 1]


array([3, 4, 7])