# Numpy (class 01) (12 - April - 2020)

# Numpy

In [2]:
import numpy as np


In [2]:
np.__version__


'1.18.1'

In [3]:
np.sum([3,5])

8

In [7]:
def abc():
    print("Hello")
def abc():
    print("Pakistan")
abc()


Pakistan


In [8]:
%history

import numpy as np
np.__version__
np.sum([3,5])
def abc:
    print("Hello")
def abc:
    print("Pakistan")
abc()
def abc:
    print("Hello")
def abc:
    print("Pakistan")
abc
def abc():
    print("Hello")
def abc():
    print("Pakistan")
abc
def abc():
    print("Hello")
def abc():
    print("Pakistan")
abc()
%history


# Python VS Numpy

In [15]:
%time list(range(20000))[:20]


Wall time: 4 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [87]:
%time list_1 = list(range(1,3000000))

Wall time: 117 ms


In [18]:
%time np.arange(20000000)

Wall time: 74.3 ms


array([       0,        1,        2, ..., 19999997, 19999998, 19999999])

In [20]:
%time [x+5 for x in range(1, 1000000)[: 20]]

Wall time: 0 ns


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

# Enumerate Function:
Enumerate() method adds a counter to an iterable and returns it in a form of enumerate object. This enumerate object can then be used directly in for loops or be converted into a list of tuples using list() method.


In [26]:
l1 = list(range(1, 100000))
l2 = enumerate(l1)
for i, v in l2:
    l1[i] = l1[i]+5
l1[:20] 


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

In [28]:
l1 = list(range(1, 100000))
l2 = enumerate(l1)
for i, v in l2:
    l1[i] = l1[i]+5
l1[:20] 

%time

Wall time: 0 ns


In [89]:
#Two Dimenstions list ADDING value 05

a =[[1,2,3],
    [4,5,6],
    [7,8,9]]
print("Before Adding 5: ")
print(a)

for ri, rd in list(enumerate(a)):
    for ci, cd in list(enumerate(rd)):
        a[ri][ci] += 5
        
    
print("\nAfter Adding 5: ")
print(a)

Before Adding 5: 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

After Adding 5: 
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [33]:
#Two Dimenstions list ADDING value 05

a = np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print("Before Adding 5: ")
print(a)

for r , rd in list(enumerate(a)):
    a[r] = a[r]+5
    
print("\nAfter Adding 5: ")
print(a)

Before Adding 5: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After Adding 5: 
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [35]:
#Two Dimenstions list ADDING value 05

a = np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print("Before Adding 5: ")
print(a)

for r , rd in list(enumerate(a)):
    for c, cd in list(enumerate(rd)):
        a[r][c] = a[r][c]+5 
    
    
print("\nAfter Adding 5: ")
print(a)

Before Adding 5: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After Adding 5: 
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# Multi-Dimensional Array

In [91]:
b = np.arange(1,10).reshape((3,3))
b = b+5
b

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [94]:
l1 = np.random.randn(2,2)
print(l1)
print("\nDimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[[-0.51975234  0.54154098]
 [ 0.29226402  0.55067033]]

Dimension: 2
Shape: (2, 2)
Type: float64


In [95]:
l1 = np.random.randn(3,3,3)
print(l1)
print("\nDimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[[[ 1.25329505  0.99527761 -1.04600372]
  [ 0.05108394 -0.54752418  0.75138263]
  [-0.45608744 -0.67224507  0.11055596]]

 [[ 0.5663857  -1.53332738  0.60671848]
  [ 0.34597542  0.74463272  1.21279313]
  [ 0.01170054 -0.91529145  1.14764207]]

 [[-0.80635479  0.21410925  1.9867548 ]
  [-0.03828669 -0.08735316 -0.56009087]
  [-0.56950943 -0.69189175 -1.58177193]]]

Dimension: 3
Shape: (3, 3, 3)
Type: float64


In [53]:
c = np.arange(1,28).reshape(3,3,3)
c = c+5
c

array([[[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32]]])

In [56]:
d = np.arange(1,28).reshape(3,3,3)
d = d%2
d

array([[[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]],

       [[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]]], dtype=int32)

In [68]:
a = np.random.randn(2,3,5,5,4,5)
print(a.ndim) #Number of Array Dimensions
print(a.shape)
a = a * 10
a

6
(2, 3, 5, 5, 4, 5)


array([[[[[[-1.30644486e+00,  3.43872801e-02, -1.55083982e+01,
            -1.12143589e+01, -1.92523618e+00],
           [ 3.25757369e+00, -1.32752812e+01, -7.79692884e+00,
             6.45124932e+00, -4.75694468e+00],
           [-1.27197297e+01, -1.26480131e+01,  1.38979956e+01,
            -5.16425903e-01, -5.69599419e+00],
           [-5.32578232e+00,  6.12916878e+00, -5.78369458e+00,
            -5.78724745e+00, -7.20527802e+00]],

          [[-3.89449999e+00, -6.74439504e+00, -5.74691855e+00,
             1.13370750e+01,  2.06295400e+00],
           [-1.37736833e+01,  1.28984268e+01,  1.45263300e+01,
             2.32581207e+00, -5.75611197e+00],
           [-1.92705288e+00,  4.81355585e+00,  1.20225088e+01,
             1.79392537e+00,  4.98827936e+00],
           [ 2.66708704e+00, -2.07603606e+00, -1.85261431e+01,
            -5.16259026e+00,  8.58257593e+00]],

          [[-7.94872667e+00,  1.18959576e+00,  5.01333317e-01,
            -3.26010157e+00, -7.11323219e-01],
      

In [102]:
a = np.arange(1,13).reshape((6,2))
print(a)

print("\n",a * a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

 [[  1   4]
 [  9  16]
 [ 25  36]
 [ 49  64]
 [ 81 100]
 [121 144]]


# a[i,j,k]
starts from zero(0)

In [104]:
a[2,1]

6

In [ ]:
MultiDimes

In [99]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)
print("\nDimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

l1[1,2,1]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Dimension: 3
Shape: (3, 3, 3)
Type: int32


16

In [3]:
l1 = np.arange(1,11)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension: 1
Shape: (10,)
Type: int32


In [4]:
l1 = np.arange(1,26).reshape((5,5))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Dimension: 2
Shape: (5, 5)
Type: int32


In [5]:
l1 = np.random.randn(3,3,3,3,3)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("itemsize", l1.itemsize)
print("Type:", l1.dtype)

[[[[[ 0.04265851  2.57722094  0.18168383]
    [ 1.14149019 -0.01693022 -0.89927988]
    [-0.16599499 -0.41840438 -0.06830131]]

   [[ 0.36017833 -0.53729107  0.45891284]
    [ 0.12656048  0.1785731   0.83224888]
    [-0.17242198  0.01847341  0.52892572]]

   [[-0.26545459  1.57952633  0.94052603]
    [-0.19139982  1.03546421 -0.20032914]
    [ 0.59780961 -0.47524236  0.13274057]]]


  [[[-0.65533637  1.59597518  0.03498419]
    [ 1.18366451  0.74112108 -0.01780961]
    [-3.16206905 -0.23915759  0.95082657]]

   [[-0.53576387  0.1616424   0.95905492]
    [ 0.49102555 -0.53530455 -0.76961681]
    [ 0.51465156  0.10921277  1.44374282]]

   [[ 0.12043296 -1.53302195  0.29681367]
    [-0.54227631  0.43631934 -1.25043402]
    [-0.6386781   1.07447559  0.30097503]]]


  [[[ 2.89503318  0.35144994  1.21820861]
    [ 0.3162634  -1.28945458 -0.12412404]
    [-0.14724392 -0.40017126  1.04417007]]

   [[-1.02874608  0.93167582 -0.50501679]
    [-0.01987192  1.2759667   2.27644565]
    [ 0.14950718

# Creating ndarrays

In [13]:
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(a is b)
type(a)

<class 'list'>
False


numpy.ndarray

# np.asarray

In [14]:
# 1 array->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy

l = [1,2,3]
print(type(l))

a = np.asarray(l) #2
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#3

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [15]:
%history

l1 = np.arange(1,11)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
import numpy as np
l1 = np.arange(1,11)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
l1 = np.arange(1,26).reshape((5,5))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
l1 = np.random.randn(3,3,3,3,3)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("itemsize", l1.itemsize)
print("Type:", l1.dtype)
Creating ndarrays
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(a is b)
type(a)
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(a is b)
#type(a)
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(a is b)
type(a)
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(b is b)
type(a)
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(b 

In [16]:
a = np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
a.data

In [19]:
id(a)

1870834389120