# Class 02 (19 - April - 2020)

In [1]:
import numpy as np
a  = np.arange(3*3*3).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [2]:
print(a[1,1,2])
print(a[1][1][2])
print(a[-2,-2,-1]) 

14
14
14


In [5]:
names = np.array(["K.A.H","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)
print(names, data, sep="\n")

['K.A.H' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[ 0.95422276 -1.09477802 -1.75673999 -0.53049521]
 [-1.929816    0.8382779   0.44623196 -0.95865852]
 [-1.40125587  0.33958482  0.94387276 -0.74847114]
 [-2.12490255  0.20403942  1.78926175  0.29900455]
 [-2.29873521  1.73196473 -0.3934112   1.85350853]
 [ 0.22551663  0.49922816  1.67618393 -0.99981611]]


In [7]:
names=="K.A.H"

array([ True, False, False, False, False, False])

In [8]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)
print(names, data, sep="\n")

data[names=="Qasim"]

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[-0.22022221 -0.94299015  0.83981853  0.18461457]
 [ 0.25904245  0.6160618   0.320522   -0.18103237]
 [ 0.90136521  2.07367715 -0.63591379 -0.02327702]
 [ 1.78865512 -2.04550551  0.29018156 -1.08893613]
 [-0.12427859  0.88434972 -0.10659304 -1.00839411]
 [ 1.68978622 -0.08209589 -1.0243976   1.77111127]]


array([[-0.22022221, -0.94299015,  0.83981853,  0.18461457],
       [-0.12427859,  0.88434972, -0.10659304, -1.00839411]])

In [9]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)

print(names, data, sep="\n")

data[names=="Qasim"][:,[-1,0,2]]

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[ 0.77162949 -1.80069761 -0.70987573  0.76632911]
 [ 0.10439604 -1.14489401 -0.6699323   0.49580558]
 [-0.69587028  0.01356026 -0.78376458  0.5072603 ]
 [ 0.4021533  -0.74072556 -1.11057556  0.73594391]
 [ 0.35060934 -0.19625831 -0.32178761  1.02598461]
 [ 0.05225612  0.02327932 -1.64342952  0.36973666]]


array([[ 0.76632911,  0.77162949, -0.70987573],
       [ 1.02598461,  0.35060934, -0.32178761]])

In [10]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)

print(names, data, sep="\n")

#data[~(names == "Qasim") | ~(names=="Ali")]
data[(names != "Qasim") | (names!="Ali")]
data[:,::-1]

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[ 1.45076799 -0.07858209 -0.76069168 -0.79467046]
 [-0.69017906 -0.69297198 -0.4381207   0.46998458]
 [ 0.68893218 -0.68333673  0.46579915 -1.51307751]
 [ 0.87922952 -1.35146234  0.29763909 -1.14682916]
 [ 1.19211861 -0.16387157  0.4124935  -0.31836115]
 [ 0.74467731 -0.86154938 -0.39809343  0.39468144]]


array([[-0.79467046, -0.76069168, -0.07858209,  1.45076799],
       [ 0.46998458, -0.4381207 , -0.69297198, -0.69017906],
       [-1.51307751,  0.46579915, -0.68333673,  0.68893218],
       [-1.14682916,  0.29763909, -1.35146234,  0.87922952],
       [-0.31836115,  0.4124935 , -0.16387157,  1.19211861],
       [ 0.39468144, -0.39809343, -0.86154938,  0.74467731]])

# Fancy Slicing

In [11]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [12]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
print()
print(a[[-1,-2,0],:,:])
print(a[[-1,-2,0]])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]
[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [13]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
print()
#print(a[:,[1,2], :])
print(a[:,1:, :])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[[ 3  4  5]
  [ 6  7  8]]

 [[12 13 14]
  [15 16 17]]

 [[21 22 23]
  [24 25 26]]]


In [14]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
a[1] = 5
a

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 5,  5,  5],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
a = np.arange(3*3).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
#a[1:,1:]
a[1:3,1:3]
#a[-2:,-2:]

array([[4, 5],
       [7, 8]])

In [17]:
a = np.arange(8*4).reshape((8,4))
print(a)
for i in range(len(a)):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [18]:
a = np.arange(8*4).reshape((8,4))
print(a)
for i in range(a.shape[0]):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [19]:
a = np.arange(8*4).reshape((8,4))
print(a)
for i, _ in enumerate(a):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [21]:
list(enumerate([8,9,10]))

[(0, 8), (1, 9), (2, 10)]

In [22]:
a

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [23]:
print(a)
a[[5,4,3]]

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


array([[5, 5, 5, 5],
       [4, 4, 4, 4],
       [3, 3, 3, 3]])

In [25]:
a = np.arange(8*4).reshape((8,4))
print(a)
a[[5,4,3]][:,[3,1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[23, 21],
       [19, 17],
       [15, 13]])

In [26]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

# Transporting Arrays and Swapping Axes

In [27]:
a = np.arange(4*3).reshape((4,3))
print(a)
print(a.T)
print(a.transpose())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [28]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a * b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[ 3  8]
 [15 24]]


In [29]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a @ b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[13 16]
 [29 36]]


In [30]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a.dot(b))

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[13 16]
 [29 36]]


In [31]:
a

array([[1, 2],
       [3, 4]])

In [32]:
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

In [33]:
a @ a.T

array([[ 5, 11],
       [11, 25]])

In [34]:
a = np.arange(27).reshape((3,3,3))
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [35]:
a.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [37]:
print(a)
print(a.transpose((2,1,0)))


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [38]:
a = np.arange(12).reshape(4,3)
print(a)
print(a.swapaxes(1,0))
#print(a.reshape((a.shape[1], a.shape[0])))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [39]:
a.ndim

2

In [41]:
a.shape

(4, 3)

# 4.2 Universal Functions: Fast Element-Wise Array Functions

In [42]:
l = np.array([-1,3,-5,8,0])
np.abs(l)

array([1, 3, 5, 8, 0])

In [43]:
l = np.array([-1,3,-5,8,0])
np.fabs(l)

array([1., 3., 5., 8., 0.])

In [44]:
np.sqrt([36,25,9])

array([6., 5., 3.])

In [45]:
np.square([2,3,4])

array([ 4,  9, 16], dtype=int32)

In [46]:
np.exp([2,3,5])

array([  7.3890561 ,  20.08553692, 148.4131591 ])

In [48]:
np.ceil([2.2, 3.1, 2.6])

array([3., 4., 3.])

In [49]:
np.floor([2.2, 3.1, 2.6])

array([2., 3., 2.])

In [50]:
a = np.array([2.2, 3.1, 2.6])
print(a)
print()
f, w = np.modf(a)
print(w,f, sep="\n\n")

[2.2 3.1 2.6]

[2. 3. 2.]

[0.2 0.1 0.6]


In [51]:
for i in [2.2, 3.1, 2.6]:
    i= str(i).split(".")
    print(i[0], i[1])

2 2
3 1
2 6


In [52]:
a = np.array([1,3,45])
b = np.array([2,4,3])

print(np.maximum(a,b))

[ 2  4 45]


In [53]:
a = np.array([1,3,45])
b = np.array([2,4,3])

np.fmax(a,b)

array([ 2,  4, 45])

In [54]:
a = np.arange(6*2).reshape((6,2))
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,

# Expressing Conditional Logic as Array Operations

In [55]:
a = np.arange(3*3*3).reshape((3,3,3))
a %3 == 0

array([[[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]]])

### np.where(condition, value_True, value_false)

In [57]:
np.where(a%3==0, "Yes","No")

array([[['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']],

       [['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']],

       [['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']]], dtype='<U3')

In [58]:
a = np.array([1,3,45])
b = np.array([2,4,3])

print(np.where(a>b, a, b))

[ 2  4 45]
